cy.visit('https://www.artofmanliness.com/');
cy.get('.aom-content').click();
cy.url().should('contains', 'https://www.artofmanliness.com/people/fatherhood/sunday-firesides-we-shouldnt-and-should-be-friends-with-our-kids/');
cy.url().should('contains', 'https://www.artofmanliness.com/featured/sunday-firesides-ad-lib-fatherhood/');
cy.url().should('contains', 'https://www.artofmanliness.com/featured/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.url().should('contains', 'https://www.artofmanliness.com/odds-ends/odds-ends-august-18-2023/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.get('.aom-latest').click();
cy.url().should('contains', 'https://www.artofmanliness.com/articles/');
cy.url().should('contains', 'https://www.artofmanliness.com/character/behavior/podcast-918-unlock-the-power-of-the-unfocused-mind/');
cy.visit('https://www.artofmanliness.com/character/behavior/podcast-918-unlock-the-power-of-the-unfocused-mind/');
cy.get('.aom-content').click();
cy.url().should('contains', 'https://www.artofmanliness.com/character/advice/podcast-849-live-life-in-crescendo/');
cy.url().should('contains', 'https://www.artofmanliness.com/living/reading/100-books-every-man-read/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.url().should('contains', 'https://www.artofmanliness.com/character/advice/beyond-sissy-resilience-on-becoming-antifragile/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.get('.aom-featured-topic:nth-child(9) > .aom-article-simple:nth-child(3)').click();
cy.get('.aom-featured-topic:nth-child(9) > .aom-article-simple:nth-child(3)').click();
cy.url().should('contains', 'https://www.artofmanliness.com/lifestyle/gear/9-things-pay-top-dollar/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.url().should('contains', 'https://www.artofmanliness.com/career-wealth/wealth/7-personal-finance-goals-for-your-30s/');
cy.url().should('contains', 'https://www.artofmanliness.com/');
cy.get('.aom-action').click();
cy.get('.aom-action').click();
cy.url().should('contains', 'https://www.artofmanliness.com/contact/');
cy.url().should('contains', 'https://www.artofmanliness.com/faq/');
cy.url().should('contains', 'https://www.artofmanliness.com/privacy-policy/');
cy.url().should('contains', 'https://www.artofmanliness.com/about-2/');
cy.url().should('contains', 'https://www.artofmanliness.com/all-topics/');
cy.url().should('contains', 'https://www.artofmanliness.com/living/food-drink/easy-crispy-chicken-sandwich/');
cy.url().should('contains', 'https://www.artofmanliness.com/all-topics/');
cy.url().should('contains', 'https://www.artofmanliness.com/style/facial-hair/');
cy.url().should('contains', 'https://www.artofmanliness.com/style/facial-hair/growing-a-manly-beard/');
cy.url().should('contains', 'https://www.artofmanliness.com/archives/');
cy.get('.aom-compact-archive-ul > li:nth-child(6)').click();
cy.url().should('contains', 'https://www.artofmanliness.com/2018/09/');
cy.url().should('contains', 'https://www.artofmanliness.com/archives/');
cy.url().should('contains', 'https://www.artofmanliness.com/2008/01/');
cy.url().should('contains', 'https://www.artofmanliness.com/character/manly-lessons/lessons-in-manliness-from-gladiator/');
cy.url().should('contains', 'https://www.artofmanliness.com/style/');
cy.url().should('contains', 'https://www.artofmanliness.com/style/accessories/');
cy.url().should('contains', 'https://www.artofmanliness.com/style/facial-hair/');
cy.url().should('contains', 'https://www.artofmanliness.com/health-fitness/');
cy.url().should('contains', 'https://www.artofmanliness.com/health-fitness/program-review/');
cy.url().should('contains', 'https://www.artofmanliness.com/people/');
cy.url().should('contains', 'https://www.artofmanliness.com/skills/');
cy.url().should('contains', 'https://www.artofmanliness.com/podcast/');
cy.get('.aom-search-label').click();
cy.get('.aom-search-input').click();
cy.get('.aom-search-input').type('macedonia');
cy.get('.aom-search-form > .aom-hidden').click();
cy.url().should('contains', 'https://www.artofmanliness.com/');
