cy.visit('https://www.formula1.com/');
cy.get('.f1-homepage--hero').click();
cy.url().should('contains', 'https://www.formula1.com/en/latest.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.dave-robson-explains-how-new-team-principal-vowles-has-refreshed-atmosphere.1YlbKY6XRkHLbTmWOYToch.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.dave-robson-explains-how-new-team-principal-vowles-has-refreshed-atmosphere.1YlbKY6XRkHLbTmWOYToch.html');
cy.url().should('contains', 'https://platform.twitter.com/widgets/widget_iframe.2b2d73daf636805223fb11d48f3e94f7.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/tags.williams.SPHhgHqWWG8mYq8eewsQU.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/tags.williams.SPHhgHqWWG8mYq8eewsQU.html');
cy.get('.js-load-more-btn').click();
cy.get('.js-load-more-btn').click();
cy.get('.js-load-more-btn').click();
cy.url().should('contains', 'https://www.formula1.com/en/page.what-is-f1.html');
cy.url().should('contains', 'https://www.formula1.com/en/page.what-is-f1.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers/sergio-perez.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers/sergio-perez.html');
cy.url().should('contains', 'https://www.formula1.com/en/page.what-is-f1.html');
cy.url().should('contains', 'https://www.formula1.com/en/page.what-is-f1.html');
cy.get('.btn--inverted:nth-child(3)').click();
cy.get('.vjs-playback-rate:nth-child(2)').dblclick();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-playback-rate:nth-child(2)').click();
cy.get('.vjs-quality-menu-button > .vjs-icon-placeholder').click();
cy.get('.vjs-quality-menu-button > .vjs-icon-placeholder').dblclick();
cy.get('.vjs-quality-menu-button > .vjs-icon-placeholder').click();
cy.get('.vjs-quality-menu-button > .vjs-icon-placeholder').click();
cy.get('.vjs-hidden > .vjs-menu-content > .vjs-selected').click();
cy.get('.vjs-quality-menu-button > .vjs-icon-placeholder').click();
cy.get('.vjs-hidden > .vjs-menu-content > .vjs-selected > .vjs-menu-item-text').click();
cy.get('.vjs-mute-control > .vjs-icon-placeholder').dblclick();
cy.get('.vjs-play-control > .vjs-icon-placeholder').dblclick();
cy.get('.close-btn').click();
cy.url().should('contains', 'https://www.formula1.com/en/teams.html');
cy.url().should('contains', 'https://www.formula1.com/en/teams.html');
cy.url().should('contains', 'https://www.formula1.com/en/teams/Mercedes.html');
cy.url().should('contains', 'https://www.formula1.com/en/teams/Mercedes.html');
cy.url().should('contains', 'https://www.formula1.com/en/gaming.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers/fernando-alonso.html');
cy.url().should('contains', 'https://www.formula1.com/en/drivers/fernando-alonso.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/team.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/team.html');
cy.get('.resultsarchive-filter-item:nth-child(2) > .selected > .clip').click();
cy.get('.resultsarchive-filter-wrap:nth-child(3) .selected').click();
cy.get('.resultsarchive-filter-item:nth-child(4) > .selected > .clip').click();
cy.get('.resultsarchive-filter-item:nth-child(2) > .selected > .clip').click();
cy.get('.resultsarchive-filter-wrap:nth-child(3) .selected > .clip').click();
cy.get('.resultsarchive-filter-wrap:nth-child(2) .selected > .clip').click();
cy.get('.resultsarchive-filter-item:nth-child(2) > .selected').click();
cy.get('.resultsarchive-filter-wrap:nth-child(3) .selected').click();
cy.get('.resultsarchive-filter-wrap:nth-child(2) .selected > .clip').click();
cy.get('.resultsarchive-filter-item:nth-child(3) > .selected > .clip').click();
cy.get('.resultsarchive-filter-wrap:nth-child(2) .selected').click();
cy.get('.resultsarchive-filter-wrap:nth-child(3) .selected > .clip').click();
cy.get('.resultsarchive-filter-item:nth-child(4) > .selected > .clip').click();
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023.html');
cy.url().should('contains', 'https://sync.ecal.com/button/v1/ecal.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Bahrain.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Bahrain.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023.html');
cy.url().should('contains', 'https://sync.ecal.com/button/v1/ecal.html');
cy.get('.cta-race-name').click();
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands.html');
cy.url().should('contains', 'https://sync.ecal.com/button/v1/ecal.html');
cy.get('.ecal-sync-widget-button').click();
cy.get('ul > .f1--xs:nth-child(2)').click();
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands/News.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands/News.html');
cy.url().should('contains', 'https://sync.ecal.com/button/v1/ecal.html');
cy.get('.f1--xs:nth-child(3)').click();
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands/Circuit.html');
cy.url().should('contains', 'https://www.formula1.com/en/racing/2023/Netherlands/Circuit.html');
cy.url().should('contains', 'https://sync.ecal.com/button/v1/ecal.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.formula-1-announces-calendar-for-2024.XL3c5Cxi0ZOQzPrUu5izL.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.formula-1-announces-calendar-for-2024.XL3c5Cxi0ZOQzPrUu5izL.html');
cy.url().should('contains', 'https://platform.twitter.com/widgets/widget_iframe.2b2d73daf636805223fb11d48f3e94f7.html');
cy.url().should('contains', 'https://platform.twitter.com/embed/Tweet.html');
cy.url().should('contains', 'https://www.formula1.com/en/page.discover-unlocked.html');
cy.url().should('contains', 'https://www.formula1.com/en/page.discover-unlocked.html');
cy.get('.col-lg-2:nth-child(2) .f1-nav__item .f1-nav__item:nth-child(1) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/races/1216/belgium/race-result.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/races/1216/belgium/race-result.html');
cy.get('.col-lg-2:nth-child(2) .f1-nav__item:nth-child(2) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/drivers.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/drivers.html');
cy.get('.col-lg-2:nth-child(2) .f1-nav__item:nth-child(3) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/team.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/2023/team.html');
cy.get('.col-lg-2:nth-child(2) .f1-nav__item:nth-child(4) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/results.html/1950/races/94/great-britain/race-result.html');
cy.url().should('contains', 'https://www.formula1.com/en/results.html/1950/races/94/great-britain/race-result.html');
cy.get('.col-lg-2:nth-child(2) .f1-nav__item:nth-child(5) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/results/awards.html');
cy.url().should('contains', 'https://www.formula1.com/en/results/awards.html');
cy.get('.col-lg-2:nth-child(3) .f1-nav__item .f1-nav__item:nth-child(1) .f1-nav__underline').click();
cy.visit('https://www.formula1.com/en/results/awards.html');
cy.get('.f1-footer__middle').click();
cy.get('.col-lg-2:nth-child(4) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/f1-live.html');
cy.url().should('contains', 'https://www.formula1.com/en/f1-live.html');
cy.get('.col-lg-2:nth-child(5) .f1-nav__item:nth-child(1) .f1-nav__underline').click();
cy.visit('https://www.formula1.com/en/f1-live.html');
cy.get('.f1-border').click();
cy.get('.col-lg-2:nth-child(5) .f1-nav__item:nth-child(3) .f1-nav__underline').click();
cy.get('.col-lg-2:nth-child(2)').click();
cy.get('.col-lg-2:nth-child(6) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.from-cutting-curfews-to-grid-penalties-10-rule-changes-you-need-to-know.5EN5ENd23oOqFDnw8fD0rp.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.from-cutting-curfews-to-grid-penalties-10-rule-changes-you-need-to-know.5EN5ENd23oOqFDnw8fD0rp.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/tags.2023-season-preview.wsmEfkIe7IwFeYK926Bd0.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/tags.2023-season-preview.wsmEfkIe7IwFeYK926Bd0.html');
cy.get('.f1-legal-links > .f1-nav__item .f1-nav__item:nth-child(1) .f1-nav__underline').click();
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.faqs-and-contact-information.1TqkueKz2aRd9diRUQlq2U.html');
cy.url().should('contains', 'https://platform.twitter.com/widgets/widget_iframe.2b2d73daf636805223fb11d48f3e94f7.html');
cy.url().should('contains', 'https://www.formula1.com/en/latest/article.faqs-and-contact-information.1TqkueKz2aRd9diRUQlq2U.html');
cy.url().should('contains', 'https://platform.twitter.com/widgets/widget_iframe.2b2d73daf636805223fb11d48f3e94f7.html');
cy.get('.f1-legal-links .f1-nav__item:nth-child(2) .f1-nav__underline').click();
cy.visit('https://www.formula1.com/en/latest/article.faqs-and-contact-information.1TqkueKz2aRd9diRUQlq2U.html');
cy.get('.col-lg-2:nth-child(2)').click();
cy.get('.f1-legal-links .f1-nav__item:nth-child(3) .f1-nav__underline').click();
cy.get('.col-lg-2:nth-child(2)').click();
cy.get('.f1-legal-links .f1-nav__item:nth-child(4) .f1-nav__underline').click();
cy.get('.col-sm-12:nth-child(2)').click();
