cy.visit('https://www.w3schools.com/');
cy.get('.learntocodecontent').click();
cy.url().should('contains', 'https://www.w3schools.com/');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_slideshow_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/html/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/exercise.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/exercise.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/exercise.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/exercise.asp');
cy.url().should('contains', 'https://www.w3schools.com/');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_slideshow_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/html/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_intro.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_editors.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_basic.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_editors.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_responsive.asp');
cy.url().should('contains', 'https://www.w3schools.com/html/html_quiz.asp');
cy.url().should('contains', 'https://www.w3schools.com/tags/ref_colornames.asp');
cy.url().should('contains', 'https://www.w3schools.com/colors/colors_mixer.asp');
cy.url().should('contains', 'https://www.w3schools.com/colors/colors_converter.asp');
cy.url().should('contains', 'https://www.w3schools.com/colors/colors_rgb.asp');
cy.url().should('contains', 'https://www.w3schools.com/css/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/css/css_intro.asp');
cy.url().should('contains', 'https://www.w3schools.com/css/demo_default.htm');
cy.url().should('contains', 'https://www.w3schools.com/css/tryit.asp');
cy.url().should('contains', 'https://www.w3schools.com/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_slideshow_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/bootcamp/index.php');
cy.url().should('contains', 'https://www.w3schools.com/bootcamp/bootcamp_web-dev.php');
cy.url().should('contains', 'https://www.w3schools.com/bootcamp/bootcamp_htmlcss.php');
cy.url().should('contains', 'https://www.w3schools.com/bootcamp/bootcamp_js.php');
cy.url().should('contains', 'https://www.w3schools.com/bootcamp/bootcamp_sql.php');
cy.visit('https://www.w3schools.com/bootcamp/bootcamp_sql.php');
cy.get('.caption:nth-child(1)').click();
cy.url().should('contains', 'https://www.w3schools.com/spaces/index.php');
cy.visit('https://www.w3schools.com/spaces/index.php');
cy.get('.ws-light-green:nth-child(4)').click();
cy.get('.w3-center:nth-child(4) > .w3-content').click();
cy.url().should('contains', 'https://www.w3schools.com/js/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/js/js_operators.asp');
cy.url().should('contains', 'https://www.w3schools.com/js/js_strings.asp');
cy.url().should('contains', 'https://www.w3schools.com/js/js_random.asp');
cy.url().should('contains', 'https://www.w3schools.com/js/js_best_practices.asp');
cy.url().should('contains', 'https://www.w3schools.com/js/tryit.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_intro.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_syntax.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_select.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_distinct.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_where.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_and_or.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_orderby.asp');
cy.url().should('contains', 'https://www.w3schools.com/sql/sql_insert.asp');
cy.url().should('contains', 'https://www.w3schools.com/python/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/python/python_intro.asp');
cy.url().should('contains', 'https://www.w3schools.com/python/python_getstarted.asp');
cy.url().should('contains', 'https://www.w3schools.com/python/python_syntax.asp');
cy.get('.w3-clear:nth-child(3)').click();
cy.url().should('contains', 'https://www.w3schools.com/java/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/java/java_variables.asp');
cy.url().should('contains', 'https://www.w3schools.com/php/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_sidenav_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_sidenav_ifr2.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_vertical_tabs_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_topnav_iframe.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_bg_change_scroll.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/default_page2.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_image_grid_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_dropdown_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_bottom_nav.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_parallax_demo.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_signup_form_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/default_page3.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_tab_header_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_countdown.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_scroll_to_top.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_portfolio_gallery_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_navbar_sticky.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_fixed_menu.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_navbar_slide.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_fixed_footer.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/default_page5.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_make_a_website_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_mega_menu_responsive_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_browser_window_ifr2.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_sidenav_buttons_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_svg_scrolldrawing.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_user_rating_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/howto_js_navbar_sticky.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_navbar_sticky.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_sidenav_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_sidenav_ifr2.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_vertical_tabs_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_js_topnav_iframe.htm');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_css_bg_change_scroll.htm');
cy.url().should('contains', 'https://www.w3schools.com/w3css/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/w3css/w3css_defaults.asp');
cy.url().should('contains', 'https://www.w3schools.com/c/index.php');
cy.url().should('contains', 'https://www.w3schools.com/cpp/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/cpp/cpp_switch.asp');
cy.url().should('contains', 'https://www.w3schools.com/cpp/cpp_for_loop.asp');
cy.url().should('contains', 'https://www.w3schools.com/cs/index.php');
cy.get('#pagetop').click();
cy.url().should('contains', 'https://www.w3schools.com/bootstrap/bootstrap_ver.asp');
cy.url().should('contains', 'https://www.w3schools.com/bootstrap4/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/howto/tryhow_website_bootstrap4_ifr.htm');
cy.url().should('contains', 'https://www.w3schools.com/react/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/react/react_intro.asp');
cy.url().should('contains', 'https://www.w3schools.com/react/react_getstarted.asp');
cy.url().should('contains', 'https://www.w3schools.com/mysql/default.asp');
cy.get('h1').click();
cy.url().should('contains', 'https://www.w3schools.com/jquery/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/excel/index.php');
cy.url().should('contains', 'https://www.w3schools.com/xml/default.asp');
cy.get('#scroll_right_btn > span').dblclick();
cy.get('#scroll_right_btn > span').click();
cy.get('#scroll_right_btn > span').click();
cy.get('#scroll_right_btn > span').click();
cy.get('#scroll_right_btn > span').click();
cy.get('#scroll_right_btn > span').dblclick();
cy.get('#scroll_right_btn > span').click();
cy.get('.ga-nav:nth-child(21)').click();
cy.url().should('contains', 'https://www.w3schools.com/django/index.php');
cy.get('.darktheme').click();
cy.get('.ga-nav:nth-child(22)').click();
cy.url().should('contains', 'https://www.w3schools.com/nodejs/default.asp');
cy.get('.ga-nav:nth-child(20)').click();
cy.url().should('contains', 'https://www.w3schools.com/r/default.asp');
cy.get('#scroll_right_btn > span').click();
cy.url().should('contains', 'https://www.w3schools.com/cybersecurity/index.php');
cy.url().should('contains', 'https://www.w3schools.com/cybersecurity/cybersecurity_crime.php');
cy.url().should('contains', 'https://www.w3schools.com/cybersecurity/cybersecurity_mapping_port_scanning.php');
cy.url().should('contains', 'https://www.w3schools.com/gen_ai/index.php');
cy.url().should('contains', 'https://www.w3schools.com/vue/index.php');
cy.url().should('contains', 'https://www.w3schools.com/sass/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/kotlin/index.php');
cy.url().should('contains', 'https://www.w3schools.com/go/index.php');
cy.url().should('contains', 'https://www.w3schools.com/aws/index.php');
cy.url().should('contains', 'https://www.w3schools.com/asp/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/mongodb/index.php');
cy.url().should('contains', 'https://www.w3schools.com/mongodb/index.php');
cy.url().should('contains', 'https://www.w3schools.com/postgresql/index.php');
cy.url().should('contains', 'https://www.w3schools.com/git/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/angular/default.asp');
cy.url().should('contains', 'https://www.w3schools.com/typescript/index.php');
cy.get('#subtopnav').click();
cy.url().should('contains', 'https://www.w3schools.com/datascience/default.asp');
cy.get('.ga-nav:nth-child(2)').click();
cy.get('#radio_darkpage').click();
cy.get('#radio_darkpage').click();
cy.get('#radio_darkcode').click();
cy.get('label:nth-child(5)').click();
cy.get('#radio_darkcode').click();
cy.get('label:nth-child(5)').dblclick();
cy.get('#radio_darkpage').click();
cy.get('.fa:nth-child(3)').click();
cy.get('.VIpgJd-ZVi9od-xl07Ob-lTBxed > span:nth-child(1)').click();
cy.get('h1').click();
cy.get('h1').click();
cy.get('.fa:nth-child(3)').click();
cy.get('.fa:nth-child(4)').click();
cy.get('#gsc-i-id1').click();
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.get('#gsc-i-id1').type('{backspace}');
cy.url().should('contains', 'https://www.w3schools.com/xml/xml_validator.asp');
cy.get('#navbtn_exercises').click();
cy.get('#nav_exercises .w3-col:nth-child(2)').click();
cy.url().should('contains', 'https://www.w3schools.com/html/html_exercises.asp');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/python/numpy/numpy_exercises.asp');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/exercises/index.php');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/quiztest/default.asp');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/exercises/index.php');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/postgresql/postgresql_exercises.php');
cy.get('#navbtn_exercises').click();
cy.url().should('contains', 'https://www.w3schools.com/postgresql/postgresql_quiz.php');
cy.get('#navbtn_tutorials').click();
cy.url().should('contains', 'https://www.w3schools.com/spaces/index.php');
cy.get('#navbtn_tutorials').click();
cy.url().should('contains', 'https://www.w3schools.com/spaces/index.php');
cy.get('#navbtn_tutorials').click();
cy.url().should('contains', 'https://www.w3schools.com/ai/default.asp');
cy.get('#navbtn_tutorials').click();
cy.get('#nav_tutorials .w3-col:nth-child(4)').click();
cy.url().should('contains', 'https://www.w3schools.com/django/django_ref_template_tags.php');
cy.get('#navbtn_certified').click();
cy.get('#navbtn_certified').click();
cy.get('#navbtn_certified').click();
cy.visit('https://www.w3schools.com/django/django_ref_template_tags.php');
cy.get('.w3-col > .w3-hide-small:nth-child(16)').click();
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/tutorials/index.php');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/references/index.php');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/spaces/index.php');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/exercises/index.php');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/quiztest/default.asp');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/signup/index.php');
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/signup/index.php');
cy.visit('https://www.w3schools.com/');
cy.get('.learntocodecontent').click();
cy.get('#navbtn_certified').click();
cy.get('#navbtn_services').click();
cy.url().should('contains', 'https://www.w3schools.com/browsers/default.asp');
cy.get('h1').click();
cy.url().should('contains', 'https://www.w3schools.com/browsers/browsers_os.asp');
cy.url().should('contains', 'https://www.w3schools.com/browsers/browsers_display.asp');
cy.get('#navbtn_services').click();
